name: Frontend CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'

env:
  ACR: acrticketk8s.azurecr.io

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        with:
          args:  -Dsonar.organization=maram-28 -Dsonar.projectKey=Maram-28_dispatch-intelligent -Dsonar.sources=frontend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Log in to ACR
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login $ACR -u "${{ secrets.ACR_USERNAME }}" --password-stdin

      - name: Build & push
        run: |
          docker build -t $ACR/ticket-frontend:${{ github.sha }} -t $ACR/ticket-frontend:latest ./frontend
          docker push $ACR/ticket-frontend:${{ github.sha }}
          docker push $ACR/ticket-frontend:latest

      - name: Deploy frontend only
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: azureuser
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/app
            docker login acrticketk8s.azurecr.io -u "${{ secrets.ACR_USERNAME }}" -p "${{ secrets.ACR_PASSWORD }}"
            docker compose pull frontend
            docker compose up -d frontend
